### 1. Machine Learning

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

#Loading the dataset 
penguins = sns.load_dataset("penguins")

# Head
print("Dataset head")
print(penguins.head())

# Shape
print("Shape")
print(penguins.shape)

# Info
print("Info")
penguins.info()

# Description
print("Description")
print(penguins.describe())

# Null values
print("Null Values")
print(penguins.isnull().sum())

# Duplicates
print("Duplicate Values")
print(penguins.duplicated().sum())

# Unique Values
print("Unique Values")
print(penguins.nunique())

# Percentage of missing values
print(f"Missing Value %\n {(penguins.isna().mean() * 100).round(2)}")

# Drop the missing values
complete = penguins.dropna(
    subset = ["species", "island", "sex",
            "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g",]
)
""".Copy()???"""

# Rows left after the drop
print(f"\nDropped = {len(penguins) - len(complete)}")

x = complete.drop(columns=["species"])
y = complete["species"]



### 2. Train / Test Split

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y,
)

### 3. Handling Missing Values

In [ ]:
from icecream import ic
from sklearn.impute import SimpleImputer

penguins_imp = penguins.copy()
num_cols = ["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"]
cat_cols = ["island", "sex"]

# Filling the missing values with median
num_imputer = SimpleImputer(strategy="median")
penguins_imp[num_cols] = num_imputer.fit_transform(penguins_imp[num_cols])

# Filling the missing values with most frequent as its a cat coloumn
cat_imputer = SimpleImputer(strategy="most_frequent")
penguins_imp[cat_cols] = cat_imputer.fit_transform(penguins_imp[cat_cols])

print(f"\nCatogorical Columns\n{penguins_imp[cat_cols]}")
print(f"\nNumerical Columns\n{penguins_imp[num_cols]}")

### 4. Encoding Categorical Values

In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Initalizing encoder into a variable
enc = OneHotEncoder(sparse_output = False, handle_unknown = "ignore")

# Converting them into True and False
island_train = enc.fit_transform(x_train[["island"]])

print(enc.get_feature_names_out(["island"]))
print(island_train.shape)
print(island_train)

### 5. Scaling Numeric Features


In [19]:
from sklearn.preprocessing import StandardScaler

# Selecting the numerical columns
num_features = [
    "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g",
]
# Scaler initialization
scaler = StandardScaler()

# Scaling the numerical values so the model perform the best
x_train_scaled = scaler.fit_transform(x_train[num_features])
x_test_scaled = scaler.fit_transform(x_test[num_features])

print(x_train_scaled)
                                     

[[ 0.16732502 -1.99231135  0.83478089  1.08239437]
 [ 1.22705014  1.25552054  0.1212471  -0.21564233]
 [ 0.87989881 -0.52063753  1.4769613   2.19499725]
 ...
 [ 0.02115604  1.25552054 -0.37822656  0.21703657]
 [ 0.80681432 -0.46989015  1.33425454  1.453262  ]
 [-1.91558298  0.90028893 -0.80634683 -0.77194377]]
